
on:
  push:
    branches:
      - master

name: Deploy Soundcloud-Alexa to AWS Lambda
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli --upgrade
        echo "Done install AWS"
        echo "Dowgrading pip to a specofic version to support install on Flask-Ask"
        python -m pip install --upgrade pip==9.0.3
    
      
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.VISHAL_AWS_LAMBDA_USER_KEY }}
        aws-secret-access-key: ${{ secrets.VISHAL_AWS_LAMBDA_USER_SEC }}
        aws-region: us-west-2
    
    - name: Build and Deploy Lambda zip      
      run: make -f resources/Makefile deploy
   

    
